name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # ===== Maven =====
      - name: Build with Maven
        if: hashFiles('**/pom.xml') != ''
        run: mvn -B -DskipTests package